server:
  port: 8080
  servlet:
    context-path: /

spring:
  application:
    name: server-01 # 服务名
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/mydb?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 115.28.136.78
    port: 6379
    password: suo2019

# security
#security:
#  basic:
#    enabled: false

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.dianer.entity

# redisson lock
#redisson:
#  address: redis://115.28.136.78:6379
#  password: Aa123456

#showSql
logging:
  level:
    com:
      example:
        mapper: debug

