server:
  port: 8080

spring:
  application:
    name: eurka-server
  security:
    user:
      name: anxminise
      password: 123456

eureka:
  instance:
    hostname: eurka-server
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${eureka.instance.hostname}:${server.port}/eureka/

