server:
  port: 9001
  servlet:
    context-path: /

spring:
  application:
    name: provider
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/mydb?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
  # 单机
  redis:
    host: 115.28.136.78
    port: 6379
    password: Aa123456


#eureka主机名，会在控制页面中显示
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7001/eureka/ # eureka注册中心服务器地址

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.dianer.entity

#showSql
logging:
  level:
    com:
      example:
        mapper: debug

